# Sample Azure DevOps pipeline using a Microsoft-hosted Ubuntu agent
trigger:
- main  # Trigger the pipeline whenever code is pushed to the main branch

variables:
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'

# Define the VM image to use (Microsoft-hosted Ubuntu agent)
pool:
  name: 'agent1'

steps:
- checkout: self  # Checkout code from the repository

- task: Maven@3  # Compile and build the project using Maven
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'compile'
  displayName: 'Compile Code'

- script: mvn test  # Run unit tests
  displayName: 'Run Unit Tests'

- task: Maven@3  # Run automation tests
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'verify'
  displayName: 'Run Automation Tests'

- task: Maven@3  # Package the application
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
  displayName: 'Package Application'

- task: CopyFiles@2  # Copy the packaged files to the staging directory
  inputs:
    SourceFolder: 'target'
    Contents: '**/*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1  # Publish build artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'myApp'
